=== jjgirotto/peids/Exercícios XML/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="livros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="livro" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string" />
                                        <xs:element name="autor" type="xs:string" />
                                        <xs:element name="ano" type="xs:int" />
                                        <xs:element name="preco" type="xs:decimal"/>
                                    </xs:sequence>
                                    <xs:attribute name="isbn" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jjgirotto/peids/Exercícios XML/biblioteca.xml
<?xml version="1.0"?>
<biblioteca xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com biblioteca.xsd">
    <livros>
        <livro isbn="i123">
            <titulo>Jogos Vorazes</titulo>
            <autor>Suzanne Collins</autor>
            <ano>2010</ano>
            <preco>10.50</preco>
        </livro>
        <livro isbn="i124">
            <titulo>Harry Potter</titulo>
            <autor>J. K. Rowling</autor>
            <ano>2001</ano>
            <preco>11.50</preco>
        </livro>
    </livros>
</biblioteca>
