=== jjgirotto/peids/Exercícios XML/escola.dtd
<!ELEMENT escola (professores, alunos)>
<!ELEMENT professores (professor+)>
<!ELEMENT professor (nome, disciplina)>
<!ATTLIST professor id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT disciplina (#PCDATA)>
<!ELEMENT alunos (aluno+)>
<!ELEMENT aluno (nome, curso)>
<!ATTLIST aluno numero ID #REQUIRED>
<!ELEMENT curso (#PCDATA)>

<!-- nome já está declarado em professor então não precisa declarar de novo -->
<!-- adicionar o + quando tiver +1 elemento -->

=== jjgirotto/peids/Exercícios XML/escola.xml
<?xml version="1.0"?>
<!DOCTYPE escola SYSTEM "escola.dtd">
<escola>
    <professores>
        <professor id="p1">
            <nome>Fabiana</nome>
            <disciplina>Programação e Integração de Serviços</disciplina>
        </professor>
        <professor id="p2">
            <nome>José</nome>
            <disciplina>Programação Visual</disciplina>
        </professor>
    </professores>
    <alunos>
        <aluno numero="a1">
            <nome>Juliana Girotto Leite</nome>
            <curso>Tecnologia e Programação de Sistemas</curso>
        </aluno>
        <aluno numero ="a2">
            <nome>Diogo Alves</nome>
            <curso>Tecnologia e Programação de Sistemas</curso>
        </aluno>
    </alunos>
</escola>
